site_name: "Репродуцируемый анализ данных: ЛШ «Прикладная когнитивная наука»"
markdown_extensions:
    - toc:
        toc_depth: 3
    - pymdownx.superfences
theme:
    name: readthedocs
    nav_style: dark
    hljs_languages:
        - yaml
